name: pull request

on:
  pull_request:
    paths:
      - 'source/**'

jobs:
  pull_request:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
      
    - name: Build
      run: dotnet build source\Ecs.CSharp.Benchmark\Ecs.CSharp.Benchmark.csproj -c Release /warnaserror

    - name: Run benchmark
      run: dotnet run --project source\Ecs.CSharp.Benchmark\Ecs.CSharp.Benchmark.csproj -c Release --filter * --job Dry
